config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root :to => 'home#index'
  mount ShopifyApp::Engine, at: '/'
  resource :amazon_account, only: [:new, :create, :edit, :update]
  resource :app, only: nil do
    post :uninstall
  end
  resources :amazon_products, only: nil do
    collection do
      put :pull
      post :push
      get :search
    end
  end
  mount Sidekiq::Web => '/sidekiq'
end

# == Route Map
#
#               Prefix Verb   URI Pattern                         Controller#Action
#                 root GET    /                                   home#index
#          shopify_app        /                                   ShopifyApp::Engine
#       amazon_account POST   /amazon_account(.:format)           amazon_accounts#create
#   new_amazon_account GET    /amazon_account/new(.:format)       amazon_accounts#new
#  edit_amazon_account GET    /amazon_account/edit(.:format)      amazon_accounts#edit
#                      PATCH  /amazon_account(.:format)           amazon_accounts#update
#                      PUT    /amazon_account(.:format)           amazon_accounts#update
# pull_amazon_products PUT    /amazon_products/pull(.:format)     amazon_products#pull
# push_amazon_products PUT    /amazon_products/push(.:format)     amazon_products#push
#      amazon_products GET    /amazon_products(.:format)          amazon_products#index
#                      POST   /amazon_products(.:format)          amazon_products#create
#   new_amazon_product GET    /amazon_products/new(.:format)      amazon_products#new
#  edit_amazon_product GET    /amazon_products/:id/edit(.:format) amazon_products#edit
#       amazon_product GET    /amazon_products/:id(.:format)      amazon_products#show
#                      PATCH  /amazon_products/:id(.:format)      amazon_products#update
#                      PUT    /amazon_products/:id(.:format)      amazon_products#update
#                      DELETE /amazon_products/:id(.:format)      amazon_products#destroy
#          sidekiq_web        /sidekiq                            Sidekiq::Web
#
# Routes for ShopifyApp::Engine:
#                 login GET  /login(.:format)                 sessions#new
#          authenticate POST /login(.:format)                 sessions#create
# auth_shopify_callback GET  /auth/shopify/callback(.:format) sessions#callback
#                logout GET  /logout(.:format)                sessions#destroy
#

app/models/amazon_account.rb
class AmazonAccount < ActiveRecord::Base
  has_many :amazon_products, class_name: 'Product', dependent: :destroy
  belongs_to :shop
  # I removed the uniqueness validation because I expect two stores to 
  # be related to the same amazon account.
  validates :merchant_id, :auth_token, presence: true #, uniqueness: true
  validates :marketplace_id, presence: true

  def api_keys
    @api_keys ||= {
      merchant_id: merchant_id,
      marketplace_id: marketplace_id,
      auth_token: auth_token
    }
  end
end

# == Schema Information
# Schema version: 20151008161652
#
# Table name: amazon_accounts
#
#  auth_token     :string
#  created_at     :datetime         not null
#  id             :integer          not null, primary key
#  marketplace_id :string
#  merchant_id    :string
#  shop_id        :integer          indexed
#  updated_at     :datetime         not null
#
# Indexes
#
#  index_amazon_accounts_on_shop_id  (shop_id)
#

app/controllers/amazon_accounts_controller.rb
class AmazonAccountsController < AuthenticatedController
  skip_before_action :amazon_account_set?

  def new

  end

  def create
    if amazon_account.save
      redirect_to session[:previous_path]
      session.delete(:previous_path)
      GetAmazonProductsJob.perform_later(amazon_account_id: amazon_account.id)
    else
      flash.alert = "The following errors prevent account saving, please correct them and try again."
      render :new
    end
  end

  def edit

  end

  def update
    if amazon_account.save
      redirect_to edit_amazon_account_path, notice: 'Updated successfully.'
    else
      flash.alert =  "The following errors prevent account saving, please correct them and try again."
      render :edit
    end
  end


  helper_method :amazon_account
  private
  def amazon_account
    return @amazon_account if @amazon_account
    @amazon_account = AmazonAccount.find_or_initialize_by(shop: current_shop)
    @amazon_account.attributes = amazon_account_params if params.has_key?(:amazon_account)
    @amazon_account
  end

  def amazon_account_params
    params.require(:amazon_account).permit(:merchant_id, :marketplace_id, :auth_token)
  end
end

app/helpers/amazon_accounts_helper.rb
module AmazonAccountsHelper
  def has_errors? record
    record.errors.any?
  end

  def error_messages record, &block
    record.errors.full_messages.each(&block)
  end
end

app/views/amazon_accounts/_form.html.erb
<% content_for :messages do %>
  <% if amazon_account.errors.any? %>
    <ul>
      <% amazon_account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>
<%= form_for amazon_account, url: amazon_account_path do |f| %>
      
      <div class="col-md-12 well">  <!-- This is the first well, and says take up all the 8 rows we have-->
        <form class="form-horizontal"> <!-- needs to wrap around all the form-groups -->
      
          <div class="form-group">
            <h4>Seller Id</h4> 
            <div class="input-group input-group-lg">
              <div class="input-group-addon border">    
                <span class="glyphicon glyphicon-sunglasses" aria-hidden="true"></span>
              </div>
                <%= f.text_field :merchant_id, class: 'form-control input-lg', placeholder: "Seller Id"  %>
            </div>
          </div> <!-- This should be good -->
          
          <div class="form-group">
            <h4>Marketplace Id</h4>
            <div class="input-group input-group-lg">
              <div class="input-group-addon border">    
                <span class="glyphicon glyphicon-globe" aria-hidden="true"></span>
              </div>
                <%= f.text_field :marketplace_id, :class => "form-control input-lg", :placeholder => "Marketplace Id" %>
            </div>
          </div>
          
          <div class="form-group">
            <h4>MWS Auth Token</h4>
            <div class="input-group input-group-lg">
              <div class="input-group-addon border">    
                <span class="glyphicon glyphicon-file" aria-hidden="true"></span>
              </div>
                <%= f.text_field :auth_token, :class => "form-control input-lg", :placeholder => "MWS Auth Token" %>
            </div>
          </div>
          
      <%= f.submit 'Save Profile', class: 'btn btn-primary btn-lg btn-block' %>
        
        </form> <!--end of the form -->
      </div> <!--this is the well and takes up the 8 columns -->

    
  
<% end %>

app/views/amazon_accounts/edit.html.erb
<div class="container-fluid">
    <div class="col-md-5 col-md-offset-3">  
      <h2>Edit your Amazon credentials</h2>
      <%= render partial: 'form', locals: { amazon_account: amazon_account } %>
    </div>
</div>

app/views/amazon_accounts/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      
      <div class="row">
        <div class="col-md-5">
         <h2>Add your Amazon credentials</h2>
          <%= render partial: 'form', locals: { amazon_account: amazon_account } %>
        </div>
      
      <div class="col-md-5 col-md-offset-1">
        <h2>Retrieve your credentials</h2>
          <div class="col-md-12 well">
            <form class="form-horizontal well-pad">
              
              <div class="form-group">
                <h4>Step 1. Sign up for <a href="https://developer.amazonservices.com/" target="_blank">Amazon MWS</a></h4>
                <%= render "shared/step1" %>
                <%= link_to "Details", "#step1", "data-toggle" => "modal", :class => "btn btn-primary btn-md" %>
              </div>
              
              <div class="form-group">
                <h4>Step 2. Allow us access to your Amazon account</h4>
                <%= render "shared/step2" %>
                <%= link_to "Details", "#step2", "data-toggle" => "modal", :class => "btn btn-primary btn-md" %>
              </div>
              
              <div class="form-group">
                <h4>Step 3. Promise your first born to Amazon by accepting their terms</h4>
                <%= render "shared/step3" %>
                <%= link_to "Details", "#step3", "data-toggle" => "modal", :class => "btn btn-primary btn-md" %>
              </div>
              
              <div class="form-group">
                <h4>Step 4. Capture all your important id's and register for ByteStand</h4>
                <%= render "shared/step4" %>
                <%= link_to "Details", "#step4", "data-toggle" => "modal", :class => "btn btn-primary btn-md" %>
              </div>
              
            </form>
          </div>
      </div>
      
     </div>
    </div>
  </div>
</div>