config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root :to => 'home#index'
  mount ShopifyApp::Engine, at: '/'
  resource :amazon_account, only: [:new, :create, :edit, :update]
  resource :app, only: nil do
    post :uninstall
  end
  resources :amazon_products, only: nil do
    collection do
      put :pull
      post :push
      get :search
    end
  end
  mount Sidekiq::Web => '/sidekiq'
end

# == Route Map
#
#               Prefix Verb   URI Pattern                         Controller#Action
#                 root GET    /                                   home#index
#          shopify_app        /                                   ShopifyApp::Engine
#       amazon_account POST   /amazon_account(.:format)           amazon_accounts#create
#   new_amazon_account GET    /amazon_account/new(.:format)       amazon_accounts#new
#  edit_amazon_account GET    /amazon_account/edit(.:format)      amazon_accounts#edit
#                      PATCH  /amazon_account(.:format)           amazon_accounts#update
#                      PUT    /amazon_account(.:format)           amazon_accounts#update
# pull_amazon_products PUT    /amazon_products/pull(.:format)     amazon_products#pull
# push_amazon_products PUT    /amazon_products/push(.:format)     amazon_products#push
#      amazon_products GET    /amazon_products(.:format)          amazon_products#index
#                      POST   /amazon_products(.:format)          amazon_products#create
#   new_amazon_product GET    /amazon_products/new(.:format)      amazon_products#new
#  edit_amazon_product GET    /amazon_products/:id/edit(.:format) amazon_products#edit
#       amazon_product GET    /amazon_products/:id(.:format)      amazon_products#show
#                      PATCH  /amazon_products/:id(.:format)      amazon_products#update
#                      PUT    /amazon_products/:id(.:format)      amazon_products#update
#                      DELETE /amazon_products/:id(.:format)      amazon_products#destroy
#          sidekiq_web        /sidekiq                            Sidekiq::Web
#
# Routes for ShopifyApp::Engine:
#                 login GET  /login(.:format)                 sessions#new
#          authenticate POST /login(.:format)                 sessions#create
# auth_shopify_callback GET  /auth/shopify/callback(.:format) sessions#callback
#                logout GET  /logout(.:format)                sessions#destroy
#

app/models/report.rb
class Report < ActiveRecord::Base
  has_many :products
end

# == Schema Information
# Schema version: 20151008161652
#
# Table name: reports
#
#  created_at        :datetime         not null
#  id                :integer          not null, primary key
#  report_request_id :string
#  updated_at        :datetime         not null
#

app/controllers/home_controller.rb
class HomeController < AuthenticatedController
  def index
  end

  helper_method :products, :product_search
  private
  def products
    return @products if @products
    product_search.search(scope: current_shop.amazon_products)
    @products = product_search.results(page: params[:page], per: params[:product_displayed])
  end

  def product_search
    @product_search ||= ProductSearch.new(query: '')
  end
end

app/views/home/_product_row.html.erb
<tr class='<%= row_class(product) %>' data-parent-id='<%= product.parent_id %>'>
  <td>
    <% if product.is_parent? %>
      <%= check_box_tag 'product_ids[]', product.id %>
    <% end %>
  </td>
  <td class='title'>
    <% if product.is_parent? %>
      <%= image_tag 'parent-plus.png', width: '20px', class: 'parent-icon', data: {'parent-id': product.id }  %>
    <% elsif product.is_variant? %>
      <%= image_tag 'child1.jpg', width: '15px', class: 'child-icon' %>
    <% end %>
    <a href='<%= product.amazon_url %>' target="_blank"> <%= product.title %> </a>
  </td>
  <td><%= product.asin %></td>
  <td><%= product.price %></td>
  <td><%= product.seller_sku %></td>
  <td><%= product.variants.count %></td>
</tr>

app/views/home/index.html.erb
<script type="text/javascript">
  ShopifyApp.ready(function(){
    ShopifyApp.Bar.initialize({
      title: "Home",
      icon: "<%= asset_path('favicon.ico') %>"
    });
  });
</script>

<div class="container-fluid">
  <div class="row">
    <div class='col-md-12'>
      <div class='buttons'>
      <%= link_to pull_amazon_products_path,
        class: 'btn btn-success btn-sm pull-products-btn',
        title: 'Pull products list form your amazon seller account.',
        disabled: pulling_amazon_products?,
        remote: true,
        method: :put do %>
          <% if pulling_amazon_products? %>
            Pulling products
          <% else %>
            Pull products
          <% end %>
        <% end %>
        <button type='button' id='push-selected' class='btn btn-primary btn-sm' title='Push selected products to shopify'>Push Selected</button>
        <%= link_to 'Push All', push_amazon_products_path(all: true), title: 'Push all products to shopify', class: 'btn btn-primary btn-sm', remote: true, method: :post %>
      </div>
    </div>
    
    <div class="col-md-12">
      <%= form_tag search_amazon_products_path, class: 'form-inline', method: :get, remote: true do %>
        <div class="pull-left">
          <%= select_tag :product_displayed, options_for_select(product_displayed, params[:product_displayed]), prompt: "Please select", class: 'form-control', onchange: 'product_displayed()' %>
        </div>
        <div class="pull-right">
          <div class="input-group">
            <%= text_field_tag :query, params[:query], class: 'form-control input-md', placeholder: 'Search' %>
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <!-- Need to escape in rendered js -->
    <div class="col-md-12">
      Total Products: <%= products.total_count %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= form_tag push_amazon_products_path, method: 'POST', remote: true, id: 'products_form' do %>
        <table class='table table-striped table-hover table-bordered table-condensed'>
          <thead>
            <th>
              <%= check_box_tag 'push_all', true, false %>
              <label for='push_all'></label>
            </th>
            <th>Title</th>
            <th>Price</th>
            <th>Seller SKU</th>
            <th># variants</th>
          </thead>
          <tbody class="product-index">
            <%= render products %>
          </tbody>
        </table>
        <div class='pagination-wrapper'>
          <div class="row">
            <div class="col-md-12 pagination-col">
              <%= paginate products, theme: 'twitter-bootstrap-3', pagination_class: 'pagination' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>