config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root :to => 'home#index'
  mount ShopifyApp::Engine, at: '/'
  resource :amazon_account, only: [:new, :create, :edit, :update]
  resource :app, only: nil do
    post :uninstall
  end
  resources :amazon_products, only: nil do
    collection do
      put :pull
      post :push
      get :search
    end
  end
  mount Sidekiq::Web => '/sidekiq'
end

# == Route Map
#
#               Prefix Verb   URI Pattern                         Controller#Action
#                 root GET    /                                   home#index
#          shopify_app        /                                   ShopifyApp::Engine
#       amazon_account POST   /amazon_account(.:format)           amazon_accounts#create
#   new_amazon_account GET    /amazon_account/new(.:format)       amazon_accounts#new
#  edit_amazon_account GET    /amazon_account/edit(.:format)      amazon_accounts#edit
#                      PATCH  /amazon_account(.:format)           amazon_accounts#update
#                      PUT    /amazon_account(.:format)           amazon_accounts#update
# pull_amazon_products PUT    /amazon_products/pull(.:format)     amazon_products#pull
# push_amazon_products PUT    /amazon_products/push(.:format)     amazon_products#push
#      amazon_products GET    /amazon_products(.:format)          amazon_products#index
#                      POST   /amazon_products(.:format)          amazon_products#create
#   new_amazon_product GET    /amazon_products/new(.:format)      amazon_products#new
#  edit_amazon_product GET    /amazon_products/:id/edit(.:format) amazon_products#edit
#       amazon_product GET    /amazon_products/:id(.:format)      amazon_products#show
#                      PATCH  /amazon_products/:id(.:format)      amazon_products#update
#                      PUT    /amazon_products/:id(.:format)      amazon_products#update
#                      DELETE /amazon_products/:id(.:format)      amazon_products#destroy
#          sidekiq_web        /sidekiq                            Sidekiq::Web
#
# Routes for ShopifyApp::Engine:
#                 login GET  /login(.:format)                 sessions#new
#          authenticate POST /login(.:format)                 sessions#create
# auth_shopify_callback GET  /auth/shopify/callback(.:format) sessions#callback
#                logout GET  /logout(.:format)                sessions#destroy
#

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        <img alt="ByteStand" src="http://s2.postimg.org/74hul1t7t/navbar_brand.png">
      </a>
    </div>
  
    <ul class="nav navbar-nav">
        <li class="passive"><a href="#">products <span class="sr-only">(current)</span></a></li>
        <li class="passive"><a href="#">profile <span class="sr-only">(current)</span></a></li>
    </ul>
  
  </div>
</nav>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Shopify Embedded Example App</title>

  <script src="//cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>
  <script type="text/javascript">
    ShopifyApp.init({
      apiKey: "<%= ShopifyApp.configuration.api_key %>",
      shopOrigin: "<%= "https://#{ @shop_session.url }" if @shop_session %>",
      debug: <%= Rails.env.development? ? 'true' : 'false' %>
    });
  </script>

  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href= "<%= root_path %>">
          <img alt="ByteStand" src="http://s2.postimg.org/74hul1t7t/navbar_brand.png">
        </a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="passive"><%= link_to 'products', root_path %><span class="sr-only">(current)</span></a></li>
          <li class="passive"><%= link_to "profile", edit_amazon_account_path %><span class="sr-only">(current)</span></a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <div class="container main" style='margin-top:50px;'>
    <div class="messages">
      <% if notice or alert or content_for?(:messages) %>
        <%= render "shared/errors" %>
      <% end %>
    </div>
    <%= yield %>
  </div>
</body>
</html>